# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(575, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBoxX1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxX1.setGeometry(QtCore.QRect(20, 20, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.comboBoxX1.setFont(font)
        self.comboBoxX1.setObjectName("comboBoxX1")
        self.comboBoxX1.addItem("")
        self.comboBoxX1.addItem("")
        self.comboBoxX2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxX2.setGeometry(QtCore.QRect(350, 20, 211, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.comboBoxX2.setFont(font)
        self.comboBoxX2.setObjectName("comboBoxX2")
        self.comboBoxX2.addItem("")
        self.comboBoxX2.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(190, 270, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 130, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 575, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.submit.clicked.connect(self.pressed)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBoxX1.setItemText(0, _translate("MainWindow", "0"))
        self.comboBoxX1.setItemText(1, _translate("MainWindow", "1"))
        self.comboBoxX2.setItemText(0, _translate("MainWindow", "0"))
        self.comboBoxX2.setItemText(1, _translate("MainWindow", "1"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "X XOR Y ="))

    def pressed(self):
        x = int(self.comboBoxX1.currentText())
        y = int(self.comboBoxX2.currentText())
        xor = (x and not y) or (not x and y)
        if xor ==True:
            xor = 1
        else:
            xor = 0
        self.label.setText("X XOR Y = " + str(xor))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
